# Generated by Django 5.1.5 on 2025-01-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('delete', 'delete'), ('draft', 'draft'), ('waiting_approval', 'waiting_approval')], default='active', max_length=50),
        ),
    ]
