# Generated by Django 5.1.5 on 2025-02-04 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_orderitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name_plural': 'Order Items'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated_by',
            new_name='updated_at',
        ),
    ]
