# Generated by Django 5.1.5 on 2025-02-06 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_orderitems_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='merchant_id',
            new_name='payment_intent',
        ),
    ]
