# Generated by Django 5.1.5 on 2025-03-17 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_puchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puchase',
            name='product',
        ),
        migrations.AddField(
            model_name='puchase',
            name='product',
            field=models.ManyToManyField(to='store.product'),
        ),
    ]
