# Generated by Django 5.1.5 on 2025-02-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_authstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authstatus',
            options={'verbose_name_plural': 'Auth Status'},
        ),
        migrations.AlterField(
            model_name='authstatus',
            name='reset_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='authstatus',
            name='verify_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
