# Generated by Django 5.1.5 on 2025-02-13 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_authstatus_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authstatus',
            old_name='is_authenticated',
            new_name='is_verified',
        ),
    ]
