# Generated by Django 5.1.5 on 2025-02-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_rename_is_authenticated_authstatus_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authstatus',
            name='verify_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
