# Generated by Django 5.1.5 on 2025-02-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_alter_authstatus_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='authstatus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='authstatus',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='authstatus',
            name='reset_token_expiry',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
