# Generated by Django 5.1.5 on 2025-02-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0008_authstatus_created_at_authstatus_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authstatus',
            name='reset_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
